version: '3.8'
services:
  web:
    build:
      # dockerfile: Dockerfile.init
      dockerfile: .docker/Dockerfile.dev
      context: ./
    command: npm run dev
    container_name: jaa-web
    ports:
      - 3000:3000
    volumes:
      - .:/app/
      - /app/node_modules/
    tty: true
    stdin_open: true
