services:
  app:
    container_name: jaa-app
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    port:
    - "3000:3000"
    expose:
    - 3000

