version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    container_name: jaa-web
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/app/
      - jaa-node_modules:/app/node_modules
    tty: true
    stdin_open: true

volumes:
  jaa-node_modules: