version: '3.8'
services:
  web:
    build:
      # dockerfile: Dockerfile.init
      dockerfile: .docker/Dockerfile.dev
      context: ./
    container_name: jaa-pf
    ports:
      - 3000:3000
    tty: true
    stdin_open: true